export enum EventTypes {
  HELLO_FROM_CONTAINER = "HELLO_FROM_CONTAINER",
  SAY_HI_BACK = "SAY_HI_BACK",

  // Sidebar
  SIDEBAR_OPENED = "SIDEBAR_OPENED",
  SIDEBAR_CLOSED = "SIDEBAR_CLOSED",
  TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR",
  OPEN_SIDEBAR = "OPEN_SIDEBAR",
  CLOSE_SIDEBAR = "CLOSE_SIDEBAR",
}
